run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - durationcheck
    - gocheckcompilerdirectives
    - gosimple
    - gosmopolitan
    - govet
    - ineffassign
    - nilerr
    - reassign
    - staticcheck
    - typecheck
    - unused
    - exhaustive
    - gochecksumtype
issues:
  exclude-rules:
    - path: '(.+)\.ragel\.go'
      linters:
        - ineffassign
        - unused
    - linters:
        - staticcheck
      text: "SA1019:"
